"""
Analytics and insights models
"""
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, JSON, Text, Enum
from sqlalchemy.sql import func
import enum
from app.models.base import Base


class InsightType(enum.Enum):
    """Types of insights generated by the system"""
    CHURN_RISK = "churn_risk"
    REVENUE_OPPORTUNITY = "revenue_opportunity"
    CAMPAIGN_ANOMALY = "campaign_anomaly"
    SEO_ISSUE = "seo_issue"
    CONVERSION_DROP = "conversion_drop"
    AD_DISAPPROVAL = "ad_disapproval"
    EMAIL_PERFORMANCE = "email_performance"
    TRAFFIC_ANOMALY = "traffic_anomaly"
    COST_SPIKE = "cost_spike"


class InsightPriority(enum.Enum):
    """Priority levels for insights"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Insight(Base):
    """
    AI-generated insights and recommendations
    This is the core table for surfacing actionable intelligence
    """
    __tablename__ = "insights"

    id = Column(Integer, primary_key=True, index=True)

    # Classification
    insight_type = Column(String, index=True)  # InsightType enum
    priority = Column(String, index=True)  # InsightPriority enum
    category = Column(String, index=True)  # marketing, product, customer, technical

    # Content
    title = Column(String)
    description = Column(Text)
    recommendation = Column(Text)

    # Impact
    estimated_impact = Column(Float, nullable=True)  # $ or % impact
    confidence_score = Column(Float)  # 0-1 confidence in this insight

    # Supporting data
    metric_name = Column(String)
    current_value = Column(Float, nullable=True)
    expected_value = Column(Float, nullable=True)
    threshold_value = Column(Float, nullable=True)

    # Source
    data_source = Column(String)  # shopify, ga4, google_ads, klaviyo
    related_entity_id = Column(String, nullable=True)
    related_entity_type = Column(String, nullable=True)  # campaign, customer, product

    # Action tracking
    status = Column(String, default="new")  # new, acknowledged, in_progress, resolved, dismissed
    acknowledged_at = Column(DateTime, nullable=True)
    resolved_at = Column(DateTime, nullable=True)

    # Alert
    alert_sent = Column(Boolean, default=False)
    alert_sent_at = Column(DateTime, nullable=True)

    # Additional context
    extra_data = Column(JSON)  # Renamed from 'metadata' (reserved in SQLAlchemy)

    # Timestamps
    detected_at = Column(DateTime, server_default=func.now(), index=True)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class GA4Metric(Base):
    """Google Analytics 4 metrics storage"""
    __tablename__ = "ga4_metrics"

    id = Column(Integer, primary_key=True, index=True)

    # Dimensions
    date = Column(DateTime, index=True)
    channel = Column(String, index=True, nullable=True)
    source = Column(String, index=True, nullable=True)
    medium = Column(String, index=True, nullable=True)
    page_path = Column(String, nullable=True)

    # Traffic metrics
    active_users = Column(Integer, default=0)
    new_users = Column(Integer, default=0)
    sessions = Column(Integer, default=0)
    pageviews = Column(Integer, default=0)

    # Engagement
    avg_session_duration = Column(Float, default=0.0)
    bounce_rate = Column(Float, default=0.0)
    engagement_rate = Column(Float, default=0.0)

    # E-commerce
    purchases = Column(Integer, default=0)
    revenue = Column(Float, default=0.0)
    add_to_carts = Column(Integer, default=0)
    checkouts = Column(Integer, default=0)

    # Calculated metrics
    conversion_rate = Column(Float, nullable=True)

    # Anomaly detection
    is_anomaly = Column(Boolean, default=False)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class SEOAudit(Base):
    """SEO audit results"""
    __tablename__ = "seo_audits"

    id = Column(Integer, primary_key=True, index=True)

    # Page info
    url = Column(String, index=True)
    page_title = Column(String)
    meta_description = Column(Text, nullable=True)

    # SEO scores
    overall_score = Column(Float)  # 0-100
    technical_score = Column(Float)
    content_score = Column(Float)
    performance_score = Column(Float)

    # Issues found
    issues = Column(JSON)  # List of issues with severity
    warnings = Column(JSON)

    # Technical metrics
    load_time = Column(Float, nullable=True)
    mobile_friendly = Column(Boolean, default=True)
    has_ssl = Column(Boolean, default=True)
    has_sitemap = Column(Boolean, default=True)

    # Content analysis
    word_count = Column(Integer, nullable=True)
    heading_structure = Column(JSON, nullable=True)
    internal_links_count = Column(Integer, default=0)
    external_links_count = Column(Integer, default=0)

    # Timestamps
    audit_date = Column(DateTime, server_default=func.now(), index=True)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class DataSyncLog(Base):
    """Track data synchronization from various sources"""
    __tablename__ = "data_sync_logs"

    id = Column(Integer, primary_key=True, index=True)

    # Sync info
    source = Column(String, index=True)  # shopify, klaviyo, ga4, google_ads
    sync_type = Column(String)  # full, incremental
    status = Column(String, index=True)  # success, failed, partial

    # Details
    records_processed = Column(Integer, default=0)
    records_created = Column(Integer, default=0)
    records_updated = Column(Integer, default=0)
    records_failed = Column(Integer, default=0)

    # Error tracking
    error_message = Column(Text, nullable=True)
    error_details = Column(JSON, nullable=True)

    # Timing
    duration_seconds = Column(Float)
    started_at = Column(DateTime, index=True)
    completed_at = Column(DateTime, nullable=True)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now())
